[package]
name = "musiclibrary-player"
version = "0.1.0"
edition = "2024"

[dependencies]
ahash = "0.8.11"
base64 = "0.22.1"
discord-rich-presence = "1.0.0"
futures-util = "0.3.31"
image = "0.25.5"
jwalk = "0.8.1"
reqwest = { version = "0.12.24", features = ["json", "rustls-tls"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
symphonia = { version = "0.5.4", features = ["all", "opt-simd"] }
tokio = { version = "1.44.1", features = ["rt-multi-thread"] }
tokio-tungstenite = "0.26.2"
toml_edit = "0.22.24"

# specify versions of transitive dependencies
crossbeam-channel = "0.5.15"
openssl = "0.10.72"

[dependencies.iced]
git = "https://github.com/isa-bai/iced"
default-features = false
features = [
    #"tiny-skia",
    #"debug",
    "auto-detect-theme",
    "wgpu",
    "image", "lazy", "tokio", "svg"
]

[dependencies.rodio]
git = "https://github.com/RustAudio/rodio.git"
rev = "64cf70b45b3097ca10ca72eccceaddbb937b24e2"
default-features = false
features = ["playback", "symphonia", "symphonia-all"]


[profile.dev]
opt-level = 0

[profile.release-opts]
inherits = "release"
codegen-units = 1
debug = false
lto = true
incremental = false
opt-level = 3
overflow-checks = false
strip = true
panic = "abort"

[profile.small]
inherits = "release"
opt-level = "z"
debug = false
strip = true
lto = true
codegen-units = 1
panic = "abort"
#RUSTFLAGS="-Zlocation-detail=none" 
#RUSTFLAGS="-Zfmt-debug=none"
# "-Zlocation-detail=none -Zfmt-debug=none"
