[package]
name = "musiclibrary-player"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.11"
image = "0.25.5"
# iced = {version = "0.13.1", features = ["debug"]}
jwalk = "0.8.1"
lazy_static = "1.5.0"
symphonia = { version = "0.5.4", features = ["all", "opt-simd"] }
tokio = { version = "1.44.1", features = ["rt-multi-thread"] }

[dependencies.iced]
git = "https://github.com/isa-bai/iced"
#rev = "bae25b74f68078e5ff74cdae717273cf315d4e90"
default-features = false
features = [
    #"tiny-skia",
    "auto-detect-theme",
    #"fira-sans",
    #"debug",
    "wgpu",
    "image", "lazy", "tokio", "svg"]

[dependencies.rodio]
git = "https://github.com/RustAudio/rodio.git"
rev = "64cf70b45b3097ca10ca72eccceaddbb937b24e2"
default-features = false
features = ["playback", "symphonia", "symphonia-all"]

# [profile.dev]
# opt-level = 0

# [profile.debug2]
# inherits = "dev"

[profile.release-opts]
inherits = "release"
codegen-units = 1
debug = false
lto = true
incremental = false
opt-level = 3
overflow-checks = false
strip = true
panic = "abort"

[profile.small]
inherits = "release"
opt-level = "z"
debug = false
strip = true
lto = true
codegen-units = 1
panic = "abort"
#RUSTFLAGS="-Zlocation-detail=none" 
#RUSTFLAGS="-Zfmt-debug=none"
# "-Zlocation-detail=none -Zfmt-debug=none"
